import type { SimpleIcon } from 'simple-icons'
import {
  siAmd,
  siAngular,
  siAnsible,
  siApachegroovy,
  siApachekafka,
  siApple,
  siAssemblyscript,
  siBun,
  siC,
  siClojure,
  siCloudflare,
  siCmake,
  siCoffeescript,
  siCplusplus,
  siCrystal,
  siCss,
  siD,
  siDart,
  siDelphi,
  siDeno,
  siDigitalocean,
  siDiscord,
  siDjango,
  siDm,
  siDocker,
  siDotnet,
  siElixir,
  siElm,
  siErlang,
  siEslint,
  siExpress,
  siFastapi,
  siFigma,
  siFlask,
  siFlutter,
  siFortran,
  siFsharp,
  siGatsby,
  siGit,
  siGithub,
  siGithubactions,
  siGnubash,
  siGo,
  siGoogle,
  siGooglecloud,
  siGraphql,
  siHaskell,
  siHeroku,
  siHtml5,
  siHuggingface,
  siJavascript,
  siJulia,
  siJupyter,
  siKotlin,
  siKubernetes,
  siLaravel,
  siLinux,
  siLua,
  siMacos,
  siMongodb,
  siMysql,
  siNestjs,
  siNetlify,
  siNextdotjs,
  siNginx,
  siNim,
  siNodedotjs,
  siNpm,
  siNuxt,
  siNvidia,
  siOcaml,
  siOpenai,
  siOpencv,
  siPerl,
  siPhp,
  siPostgresql,
  siPuppet,
  siPython,
  siPytorch,
  siR,
  siReact,
  siRedis,
  siRuby,
  siRubyonrails,
  siRust,
  siSass,
  siScala,
  siScikitlearn,
  siSlack,
  siSpringboot,
  siSupabase,
  siSvelte,
  siSwift,
  siTailwindcss,
  siTampermonkey,
  siTensorflow,
  siTerraform,
  siTwitch,
  siTypescript,
  siVercel,
  siVite,
  siVuedotjs,
  siWebassembly,
  siWebpack,
  siZig,
} from 'simple-icons'

import {
  customAmazon,
  customAWS,
  customCsharp,
  customJava,
  customMicrosoft,
  customMicrosoftAzure,
  customPowershell,
  customVisualStudio,
  customVSCode,
} from './customIcons'

export const LANGUAGE_ICON_MAPPING: { [key: string]: SimpleIcon } = {
  // GitHub Linguist languages in alphabetical order
  AssemblyScript: siAssemblyscript,
  C: siC,
  'C#': customCsharp,
  'C++': siCplusplus,
  CMake: siCmake,
  Clojure: siClojure,
  CoffeeScript: siCoffeescript,
  Crystal: siCrystal,
  CSS: siCss,
  D: siD,
  Dart: siDart,
  Delphi: siDelphi,
  DM: siDm,
  Dockerfile: siDocker,
  Elixir: siElixir,
  Elm: siElm,
  Erlang: siErlang,
  'F#': siFsharp,
  Fortran: siFortran,
  Go: siGo,
  Groovy: siApachegroovy,
  Haskell: siHaskell,
  HTML: siHtml5,
  Java: customJava,
  JavaScript: siJavascript,
  Julia: siJulia,
  'Jupyter Notebook': siJupyter,
  Kotlin: siKotlin,
  Lua: siLua,
  Nginx: siNginx,
  Nim: siNim,
  OCaml: siOcaml,
  Perl: siPerl,
  PHP: siPhp,
  PowerShell: customPowershell,
  Puppet: siPuppet,
  Python: siPython,
  R: siR,
  Ruby: siRuby,
  Rust: siRust,
  Scala: siScala,
  Shell: siGnubash,
  Svelte: siSvelte,
  Swift: siSwift,
  TypeScript: siTypescript,
  Vue: siVuedotjs,
  WebAssembly: siWebassembly,
  Zig: siZig,

  // Custom Frameworks, Libraries, Tools and Platforms
  Amazon: customAmazon,
  AMD: siAmd,
  Angular: siAngular,
  Ansible: siAnsible,
  Apple: siApple,
  AWS: customAWS,
  Bun: siBun,
  Cloudflare: siCloudflare,
  Deno: siDeno,
  DigitalOcean: siDigitalocean,
  Discord: siDiscord,
  Django: siDjango,
  Docker: siDocker,
  ESLint: siEslint,
  Express: siExpress,
  FastAPI: siFastapi,
  Figma: siFigma,
  Flask: siFlask,
  Flutter: siFlutter,
  Gatsby: siGatsby,
  Git: siGit,
  'GitHub Actions': siGithubactions,
  GitHub: siGithub,
  Google: siGoogle,
  'Google Cloud': siGooglecloud,
  GraphQL: siGraphql,
  Heroku: siHeroku,
  'Hugging Face': siHuggingface,
  Kafka: siApachekafka,
  Kubernetes: siKubernetes,
  Laravel: siLaravel,
  Linux: siLinux,
  macOS: siMacos,
  MongoDB: siMongodb,
  Microsoft: customMicrosoft,
  'Microsoft Azure': customMicrosoftAzure,
  MySQL: siMysql,
  NestJS: siNestjs,
  '.NET': siDotnet,
  Netlify: siNetlify,
  'Next.js': siNextdotjs,
  'Node.js': siNodedotjs,
  NPM: siNpm,
  Nuxt: siNuxt,
  Nvidia: siNvidia,
  OpenAI: siOpenai,
  OpenCV: siOpencv,
  PostgreSQL: siPostgresql,
  PyTorch: siPytorch,
  React: siReact,
  Redis: siRedis,
  'Ruby on Rails': siRubyonrails,
  Sass: siSass,
  'scikit-learn': siScikitlearn,
  Slack: siSlack,
  'Spring Boot': siSpringboot,
  Supabase: siSupabase,
  Tailwind: siTailwindcss,
  TensorFlow: siTensorflow,
  Tampermonkey: siTampermonkey,
  Terraform: siTerraform,
  Twitch: siTwitch,
  Vercel: siVercel,
  Vite: siVite,
  'Visual Studio': customVisualStudio,
  VSCode: customVSCode,
  Webpack: siWebpack,
  Windows: customMicrosoft,
}
